apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
    spec:
      containers:
        - name: teste
          image: teste:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000 
